export const empType = {
    GET_DATA: 'GET_EMP',
    GET_DATA_SUCCESS: 'GET_EMP_SUCCESS',
    GET_DETAIL: 'GET_DETAIL',
    GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCES',
    GET_DETAIL_FAILED: 'GET_DETAIL_FAILED',
    ADD_DATA: 'ADD_EMP',
    ADD_DATA_SUCCESS: 'ADD_EMP_SUCCESS',
    ADD_DATA_FAILED: 'ADD_EMP_FAILED',
    DEL_DATA: 'DEL_EMP',
    DEL_DATA_SUCCES: 'DEL_EMP_SUCCESS',
    DEL_DATA_FAILED: 'DEL_EMP_FAILED'
}