export const workType = {
    GET_WORK_ORDER: 'GET_WORK_ORDER',
    GET_WORK_ORDER_SUCCESS: 'GET_WORK_ORDER_SUCCESS',
    GET_WORK_ORDER_FAILED: 'GET_WORK_ORDER_FAILED',
    GET_DETAIL: 'GET_WORK_DETAIL',
    GET_DETAIL_SUCCESS: 'GET_WORK_DETAIL_SUCCESS',
    GET_DETAIL_FAILED: 'GET_WORK_DETAIL_FAILED',
    SERVICE_WORK: 'GET_SERVICE_WORK',
    SERVICE_WORK_SUCCESS: 'SERVICE_WORK_SUCCESS',
    SERVICE_WORK_FAILED: 'SERVICE_WORK_FAILED'
}