import Layouts from '@/layouts/layout'
import WithAuth from '@/PrivateRoute/WithAuth'
import { doGetUserOrder } from '@/Redux/Action/Resto/userOrderAction'
import { Breadcrumb } from 'antd'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'

function Bill() {
    let router = useRouter();
    const dispatch = useDispatch();
    const [result, setResult] = useState({
        ormeNumber: '',
        subtotal: 0,
        tax: 0,
        total: 0
    })

    const userLoggedIn = useSelector((state: any) => state.GetUserReducer.getUser);
    const orderFromUser = useSelector((state: any) => state.userOrderReducer.userOrder);

    //   console.log(userLoggedIn,'user');

    useEffect(() => {
        // get order number fom local storage
        const orderFromlocalstorage = localStorage.getItem('result');
        const parsedOrderNumber = orderFromlocalstorage !== null ? JSON.parse(orderFromlocalstorage) : []
        const userid = userLoggedIn[0]?.user_id;
        const data = {
            ormeNumber: parsedOrderNumber.ormeNumber,
            userId: userid
        }

        setResult(parsedOrderNumber)
        dispatch(doGetUserOrder(data))
    }, [])

    // back page
    function back() {
        router.back()
    }
    function back2() {
        router.back()
        router.back()
    }
    return (
        <>
            <Head>
                <title>Hotel App | Restaurant</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/Hotel_Icon.png" />
            </Head>
            <main>

                <Layouts>
                    <Breadcrumb className='pb-5'>
                        <Breadcrumb.Item><a href='/restaurant'>Restaurant</a></Breadcrumb.Item>
                        <Breadcrumb.Item><a onClick={back2}>Menu</a></Breadcrumb.Item>
                        <Breadcrumb.Item><a onClick={back}>Order</a></Breadcrumb.Item>
                        <Breadcrumb.Item>Bill</Breadcrumb.Item>
                    </Breadcrumb>
                    <div className='w-2/5 border rounded-lg shadow p-4 mx-auto'>
                        <p className='text-xl text-center font-bold'>Item Ordered</p>
                        <p className='text-lg text-center'>Hotel Realta</p>
                        <p className='text-center mb-3'>{result.ormeNumber}</p>
                        <hr />
                            {
                                orderFromUser && orderFromUser.map((order: any) =>
                                    <div className=' mt-2 my-2 hover:bg-slate-100 flex'>
                                        <div className=' mt-1 w-full'>
                                            <div className='flex'>
                                                <p className='font-bold w-4/5 '>
                                                    {order.reme_name}
                                                    <span className='text-red-400 ml-4'>
                                                        x {order.orme_qty}

                                                    </span>
                                                </p>
                                            </div>
                                            <p>{order.orme_price}</p>
                                            <p>Subtotal: {order.orme_subtotal}</p>
                                        </div>

                                    </div>
                                )
                            }
                         
                        <div className='mt-6'>
                            <table className='py-5 bg-slate-100 w-full'>
                                <p className='font-bold text-center py-4 text-lg'>Payment Summary</p>
                                <tbody>
                                    <div className='p-4'>
                                        <tr className='hover:bg-slate-300' >
                                            <td className='w-full'>Sub total</td>
                                            <td className='text-right'>Rp.{result.subtotal.toLocaleString('id-ID')}</td>
                                        </tr>
                                        {/* <tr className='hover:bg-slate-300'>
                                            <td>Discount [dapet dr manaa?]</td>
                                            <td className='text-right'>Rp.0</td>
                                            </tr> */}
                                        <tr className='hover:bg-slate-300'>
                                            <td className=' py-2'>Tax(11%)</td>
                                            <td className='text-right'>{result.tax.toLocaleString('id-ID')}</td>
                                        </tr>
                                        <tr className='font-bold hover:bg-slate-300'>
                                            <td className=' py-2'>Total payment</td>
                                            <td className='text-right'>Rp.{result.total.toLocaleString('id-ID')}</td>
                                        </tr>
                                    </div>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </Layouts>
            </main>
        </>
    )
}

export default WithAuth(Bill);