import Layouts from '@/layouts/layout'
import { Breadcrumb } from 'antd'
import Head from 'next/head'
import React from 'react'
import Image from 'next/image'

export default function order() {
  
  const data = {
    tanggal: '2/2/2023',
    hotel: 'Hotel Re',
    resto: 'Lobby Lounge',
    noorder: 'MENUS#20230202-0001'
  }


  const orders = [
        {
            nama: 'Teh manis',
            desc: 'teh berasa manis',
            harga: 5000,
            qty: 2,
            subtotal: 10000
        },
        {
            nama: 'Nasi Padang',
            desc: 'Nasi dengan lauk daging sapi atau ayam',
            harga: 15000,
            qty: 2,
            subtotal: 30000
        }
    ]

    const amount = {
        subtotal_order: 40000,
        disc: -1000,
        total: 39000
    }
  return (
    <>
        <Head>
            <title>Hotel App | Restaurant Order</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main>
            <Layouts>
                <div className='container mx-auto'>
                    <Breadcrumb>
                        <Breadcrumb.Item><a href='/restaurant'>Restaurant</a></Breadcrumb.Item>
                        <Breadcrumb.Item><a href='/restaurant/menu'>Menu</a></Breadcrumb.Item>
                        <Breadcrumb.Item>Order</Breadcrumb.Item>
                    </Breadcrumb>

                    <div className='pt-5'>
                        <Image src='/assets/Hotel_Icon.png' alt='icon app' width={100} height={100}></Image>
                        <p className='text-xl text-center font-bold'>Pembayaran hotel app</p>
                        <p className='text-md font-bold'>{ data.hotel}, {data.resto}</p>
                        <p>Tanggal: {data.tanggal}</p>
                        <p>No order: {data.noorder} </p>

                        <table className='table-auto border-collapse border border-slate-400 rounded-lg my-5 mx-auto w-full'>
                            <thead>
                                <tr className='bg-slate-100'>
                                    <th className='border border-slate-300 w-96 py-3'>Menu Makanan</th>
                                    <th className='border border-slate-300 w-24'>Qty</th>
                                    <th className='border border-slate-300 w-40'>Harga</th>
                                    <th className='border border-slate-300 w-40'>Sub Total</th>
                                </tr>
                            </thead>
                            <tbody>
                              {
                                orders.map( order => 
                                    <tr>
                                        <td className='border border-slate-300 py-2 pl-2'>{order.nama}</td>
                                        <td className='border border-slate-300 text-center'>{order.qty}</td>
                                        <td className='border border-slate-300 text-right pr-3'>{order.harga}</td>
                                        <td className='border border-slate-300 text-right pr-3'>{order.subtotal}</td>
                                    </tr>
                                )
                              }
                                    <tr className='font-bold'>
                                        <td className='border border-slate-300 py-2 pl-2' colSpan={3}>Subtotal Order</td>
                                        <td className='border border-slate-300 text-right pr-3'>{amount.subtotal_order}</td>
                                    </tr>
                                    
                                    <tr className='font-bold'>
                                        <td className='border border-slate-300 py-2 pl-2' colSpan={3}>Discount</td>
                                        <td className='border border-slate-300 text-right pr-3'>{amount.disc}</td>
                                    </tr>
                                    
                                    <tr className='font-bold bg-slate-100   '>
                                        <td className='border border-slate-300 py-2 pl-2' colSpan={3}>Total Amount</td>
                                        <td className='border border-slate-300 text-right pr-3'>{amount.total}</td>
                                    </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </Layouts>
        </main>
    </>
  )
}
