const BookingConstant = {
    GET_SPOF : 'GET_SPOF',
    GET_SPOF_SUCCESS : 'GET_SPOF_SUCCEESS',
    GET_SPOF_FAILED : 'GET_SPOF_FAILED',

    GET_BOOR : 'GET_BOOR',
    GET_BOOR_SUCCESS : 'GET_BOOR_SUCCESS',
    GET_BOOR_FAILED : 'GET_BOOR_FAILED',

    INSERT_BOOKING_ORDER : 'INSERT_BOOKING_ORDER',
    INSERT_BOOKING_ORDER_SUCCESS : 'INSERT_BOOKING_ORDER_SUCCESS',
    INSERT_BOOKING_ORDER_FAILED : 'INSERT_BOOKING_ORDER_SUCCESS'
}

export default BookingConstant